338 change default betting strategy from amount == tiny bet direction == yes if p yes 05 to use kelly bet
gnosis/prediction-market-agent-tooling pull request #352
Opened 2024-08-20 17:39 UTC by gabrielfior

2024-08-20 21:42 UTC, gabrielfior commented
Closes https://github.com/gnosis/prediction-market-agent-tooling/issues/309

2024-08-21 07:38 UTC, kongzii commented on prediction_market_agent_tooling/deploy/agent.py
> +        check_not_none(self.strategy)
Why would strategy be None?

```suggestion
```

2024-08-21 07:38 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        if isinstance(market, ManifoldAgentMarket):
If we have market class here, why not just

```
return market.get_tiny_bet_amount()
```

as we had before?

2024-08-21 07:38 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +class FixedBetBettingStrategy(BettingStrategy, metaclass=ABCMeta):
This is no longer abstract class, or is it?
```suggestion
class FixedBetBettingStrategy(BettingStrategy):
```

2024-08-21 07:38 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +class KellyBettingStrategy(BettingStrategy, metaclass=ABCMeta):
Same here
```suggestion
class KellyBettingStrategy(BettingStrategy):
```

2024-08-21 07:38 UTC, kongzii commented on prediction_market_agent_tooling/markets/data_models.py
> +class KellyResult(BaseModel):
Shouldn't KellyResult be defined in `prediction_market_agent_tooling/tools/betting_strategies/kelly_criterion.py`?

2024-08-21 07:38 UTC, kongzii commented on prediction_market_agent_tooling/tools/web3_utils.py
> +        match="(.*wrong transaction nonce.*)|(.*Invalid.*)|(.*OldNonce.*)|(AlreadyKnown.*)"
When AlreadyKnown happens?

2024-08-21 07:38 UTC, kongzii commented on pyproject.toml
> +eth-ape = "^0.8.12"
These aren't only dev dependencies anymore?

2024-08-21 07:38 UTC, kongzii commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
Maybe we can keep the `.get_tiny_bet_amount` so that `0.0001` is defined on one place instead of two?

2024-08-21 11:21 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/agent.py
> +                amount_and_direction = self.calculate_bet_amount_and_direction(
It feels to me odd that we're computing an `Answer` above with `result = self.answer_binary_market(market)` (which already contains a bet direction == `result.decision`) and then computing a direction again here.

Not sure how much of a can of worms that is to refactor, but I think that should come first (or as part of this PR)

2024-08-21 11:21 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/agent.py
> +                    f"Placing bet on {market} with direction {amount_and_direction.direction} and amount {amount_and_direction.amount}"
Is `amount_and_direction.direction` guaranteed to match `result.decision`?

2024-08-21 11:21 UTC, evangriffiths commented on ape-config.yaml
> +      uri: https://rpc.gnosischain.com
Would be great for this (and deps changes) to be a separate PR, as it's unrelated to this betting strategy stuff

2024-08-21 14:17 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/agent.py
> +                    f"Placing bet on {market} with direction {amount_and_direction.direction} and amount {amount_and_direction.amount}"
In the default case (`FixedBetBettingStrategy`), yes.
In the `KellyBettingStrategy`, we overwrite the direction and they might not match.

2024-08-21 14:21 UTC, gabrielfior commented on ape-config.yaml
> +      uri: https://rpc.gnosischain.com
Sure.
https://github.com/gnosis/prediction-market-agent-tooling/issues/355

2024-08-21 14:27 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/agent.py
> +                amount_and_direction = self.calculate_bet_amount_and_direction(
That's an important aspect.
>It feels to me odd that we're computing an Answer above with result = self.answer_binary_market(market) (which already contains a bet direction == result.decision) and then computing a direction again here.

We need the Answer because it contains `estimated_p_yes`, required by the Kelly criterion (which can then revert the direction). To compare that with an agent case, the TTA creates an Answer object with a "black-box" logic - if we provide the Kelly strategy, then that's how we want to calculate bet sizes | direction.

Another idea I see is having the agents simply output `p_yes`, `rationale`, etc but NOT directions. In this case it's clear how direction was defined.
Problem with that is that `FixedBettingStrategy` copies direction from Answer - so in this case, we would need a logic for deciding direction (e.g. `p_yes` > 0.5, go YES) or similar, but also observing the market `p_yes`.

2024-08-21 14:29 UTC, gabrielfior commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
abstracted to a common variable and refactored both usages

2024-08-21 14:32 UTC, gabrielfior commented on prediction_market_agent_tooling/tools/web3_utils.py
> +        match="(.*wrong transaction nonce.*)|(.*Invalid.*)|(.*OldNonce.*)|(AlreadyKnown.*)"
Reverted. This will get done on https://github.com/gnosis/prediction-market-agent-tooling/issues/356.
For context - `AlreadyKnown` happened when a tx with the same parameters (method, args, nonce) was already present in the RPC mempool (due to the fact that the agent was running at the same time on GCP), hence the RPC outputs "I have seen this transaction before and will process it".

2024-08-21 14:36 UTC, gabrielfior commented on prediction_market_agent_tooling/markets/data_models.py
> +class KellyResult(BaseModel):
Moved.

2024-08-21 14:38 UTC, kongzii commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
But why not just keep `get_tiny_bet_amount` as it is and use that? What was the motivation to remove it? (is there a need for that? from the code it doesn't look like it)

We have `AgentMarket` as a abstract class that our agents can work with, if something is subclass of `AgentMarket`, agent should just work with it (if all methods are implemented correctly).

But now, if we introduce a new `SomeNewMarket(AgentMarket)`, it's not clear that there are places in the code where we accept AgentMarket, yet it won't work.

2024-08-21 14:38 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        if isinstance(market, ManifoldAgentMarket):
My approach here was to have a class `Strategy` handling bet sizing - it can use MarketType as part of its logic (represented by `isisntace`), however it does not have to (see Kelly case).

2024-08-21 14:41 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        if isinstance(market, ManifoldAgentMarket):
The strategy can use `get_tiny_bet_amount`, so why not? And do market-checking-logic in strategies where it's needed.

2024-08-21 14:46 UTC, gabrielfior commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
It was an implementation decision. Certainly `get_tiny_bet_amount` used to work, but in your example, if we have a new market (`Polymarket(AgentMarket)`, we would have to overwrite `get_tiny_bet_amount` implementation for that subclass - same here, we extend the logic on the FixedBettingStrategy. This is always needed because the bet_amount involves currency, which is different from market type to market type.

> But now, if we introduce a new SomeNewMarket(AgentMarket), it's not clear that there are places in the code where we accept AgentMarket, yet it won't work.
The same will happen, only the exception will be different - `NotImplementedError` vs `ValueError` (from the Strategy `get_max_bet_amount_for_market`).

2024-08-21 14:56 UTC, kongzii commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
> This is always needed 

It was needed, but the difference is that it was forced. Because AgentMartet class has many such methods: 

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/5a481ccf-268a-40f4-880b-f98ab8c91a7e)

So, if we add new market support, it should be as hard as possible to forget about something. 

That was the idea behind AgentMarket. If we go with this other way of doing things, we will need to keep track of all the places around the code that need an update to make them work with basic agent stuff. And then AgentMarket class could be removed.

2024-08-21 15:10 UTC, kongzii commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
> I can create a class without any warnings from the IDE

I assume one would scan through the `AgentMarket` class to check out what needs to be implemented, not just subclass it and hope for the best. But you are right that it would be great to have some kind of warning there.

And seems like that can be achieved easily:

1. Make it an abstract class: `class AgentMarket(BaseModel, ABC):`
2. Add @abstractmehod decorator
3. Profit:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/891ffbb9-7098-4cdd-b297-fe5ce1a03359)

@coderabbitai please create an issue to do this everywhere where we use the NotImplemented pattern.

> I have an idea that uses mypy and generics, will try it out and ask for your input.

I mean, you can, but then will you change all the `Subclass needs to implement this` methods in AgentMarket? That's kind of a big refactor for something that's not actually required for this PR 🤷 And @evangriffiths put a lot of work into AgentMarket class back then; I think he experimented with many approaches before we stuck with this one.

2024-08-21 15:23 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/agent.py
> +                amount_and_direction = self.calculate_bet_amount_and_direction(
> Another idea I see is having the agents simply output p_yes, rationale, etc but NOT directions.

Yes, this one!! This is the refactor I meant in the description for the ticket (https://github.com/gnosis/prediction-market-agent-tooling/issues/338#issue-2451317112) 😁 (sorry if it wasn't very clear).

2024-08-21 16:12 UTC, kongzii commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
Yeah, it seems like a misunderstanding.

`KellyBettingStrategy` is great; no change is needed there from my point of view.

`FixedBetBettingStrategy` could be renamed to `TinyBetStrategy` and use the `get_tiny_bet_amount` method of the market class. It makes sense to me that `TinyBetStrategy` would be the default strategy, because it's safe, and it will just work with arbitrary AgentMarket.

`FixedBetBettingStrategy` can exist as well, but it would take a `amount` argument in its `__init__` method, and again, it doesn't have to use any `get_tiny_bet_amount`-like implementation, just return the fixed value.

wdyt?

2024-08-21 16:19 UTC, gabrielfior commented on scripts/sell_all_omen.py
> +            amount=0.00001, currency=OmenAgentMarket.currency
I implemented a mix, see https://github.com/gnosis/prediction-market-agent-tooling/pull/352/commits/683b95ff0015ea770263ff7dfc1cd0fa7cb871f9#diff-ebe828b1c77960ecaea62858ada5f1ee0b662b19051aa2ffbf92cd6ea6287110R25

I like the idea of using `get_tiny_bet_amount`, because this will break (mypy will complain) if another AgentMarket is implemented which does not have the method `get_tiny_bet_amount`. Together with ABC from the other issue, this is robust enough for me.

2024-08-21 16:22 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/agent.py
> +                amount_and_direction = self.calculate_bet_amount_and_direction(
Makes sense. Removed `direction` from Answer and adapted the method, will change this in PMA when agents produce Answers.

2024-08-21 20:09 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/agent.py
> +                amount_and_direction = self.calculate_bet_amount_and_direction(
Implemented this, see `ProbabilisticAnswer` - also adapted PMA to restrain the agent from producing `Direction` - this will be done by the Strategy itself using `estimate_p_yes` and `market.current_p_yes`

2024-08-21 22:28 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        pass
Tests will still be added before merging

2024-08-22 06:21 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        self, market: T, bet_amount: float, bet_choice: str
Why not just accept `AgentMarket`?

2024-08-22 06:24 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +            (1 - estimate_p_yes) * num_tokens_no
Shouldn't this be calculated using $ value instead of token (shares) value?

2024-08-22 10:27 UTC, kongzii commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +            calculator = ManifoldDirectionCalculator()
I'd say `FixedBetBettingStrategy` shouldn't use this new direction strategy because that will change current behavior for all agents, and we didn't want to do that, or?

2024-08-22 13:36 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +            calculator = ManifoldDirectionCalculator()
ToDo
- Create FixedStrategy (P.0.5, bet yes, else bet no)
- ExpectedValue is an additional agent (like Kelly)

2024-08-23 13:44 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +            calculator = ManifoldDirectionCalculator()
@evangriffiths proved that expected_value considerations are equivalent to the condition
```
bet TRUE if estimate_p_yes > market.p_yes else bet FALSE
```
hence implemented this as default on `FixedBetBettingStrategy`, which is the default for all agents.

2024-08-23 13:46 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        if isinstance(market, ManifoldAgentMarket):
This discussion was answered on a comment in another [thread](https://github.com/gnosis/prediction-market-agent-tooling/pull/352#discussion_r1725174278) - thus closing this

2024-08-23 16:17 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +)  # Not possible to use bound due to OmenMarket and ManifoldMarket not sharing a base class
Looks like this is unused, so can remove
```suggestion
```

2024-08-23 16:17 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +    def get_max_bet_amount_for_market() -> float:
I think it makes more sense for `max_bet_amount: float` to be an attribute of the class, settable in the `__init__` method:

```
class KellyBettingStrategy(BettingStrategy):
    def __init__(
            self,
            max_bet_amount: float = 10, # Currency-independent
        ):
        super().__init__()
        self.max_bet_amount = max_bet_amount

    ...
```
so agents can choose their own max bet size if they'd like (e.g. depending on their wallet size/risk level)

2024-08-23 16:17 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        return 10  # Mana or xDAI
Or poly-whatever-it's-called! The list might get bigger/smaller, so no need to mention specific currencies.
```suggestion
        return 10
```

2024-08-23 16:17 UTC, evangriffiths commented on pyproject.toml
> +ape-foundry = "^0.8.4"
These look unrelated to this PR

2024-08-23 16:17 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +class FixedBetBettingStrategy(BettingStrategy):
Are you set on 'FixedBet' as a name? If not, just suggesting 'MaxAccuracy', because this is the strategy that will give you the highest accuracy (% correct bets) possible.

2024-08-23 16:17 UTC, evangriffiths commented on prediction_market_agent_tooling/tools/betting_strategies/kelly_criterion.py
> +) -> KellyResult:
You don't like KellyBet? 😢  It's what they call it on wikipedia ("The kelly bet is...")

2024-08-23 16:48 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +class FixedBetBettingStrategy(BettingStrategy):
Happy to rename this. MaxAccuracy approved.

2024-08-23 16:49 UTC, gabrielfior commented on prediction_market_agent_tooling/tools/betting_strategies/kelly_criterion.py
> +) -> KellyResult:
KellyBet works, result is anyways too broad. Accepted.

2024-08-23 16:50 UTC, gabrielfior commented on pyproject.toml
> +ape-foundry = "^0.8.4"
I just upgraded versions

2024-08-23 21:04 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        return 10
dude you literally just copied my comment from earlier https://github.com/gnosis/prediction-market-agent-tooling/pull/352/files#r1729201133

2024-08-23 21:07 UTC, evangriffiths commented on pyproject.toml
> +ape-foundry = "^0.8.4"
how come?

2024-08-23 21:16 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        bet_amount = market.get_tiny_bet_amount().amount
oo, similar to https://github.com/gnosis/prediction-market-agent-tooling/pull/352/files#r1729201133, I think it makes more sense for the bet amount here to be configurable, with tiny as default (although this needs a bit of fiddling for it to work):
```
class MaxAccuracyBettingStrategy(BettingStrategy):
    def __init__(
        self,
        bet_amount: amount: Union[float, Literal["tiny"]] = "tiny",
    ):
        super().__init__()
        self.bet_amount = bet_amount

    def calculate_bet_amount_and_direction(
        self, answer: ProbabilisticAnswer, market: AgentMarket
    ) -> TokenAmountAndDirection:
        bet_amount = market.get_tiny_bet_amount().amount if self.bet_amount == "tiny" else self.bet_amount
        ...
```

2024-08-23 21:17 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        return 10
no worries, i'm sorry for being rude

2024-08-23 21:22 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        bet_amount = market.get_tiny_bet_amount().amount
I thought None instead of "tiny" would be more practical - I assume it's also easier for the general agent to understand None or fixed value instead of tiny.
Let me know if you accept this variant.

2024-08-23 21:36 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +    def __init__(self, bet_amount: float | None = None):
no a big deal, but I'm not sure about bet_amount being on the base class. because in the KellyBettingStrategy case, you're specifying a 'max bet amount', which is different to how much you actually bet

2024-08-23 21:40 UTC, evangriffiths commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        bet_amount = market.get_tiny_bet_amount().amount
oo yes that's better!

2024-08-23 21:43 UTC, evangriffiths approved these changes
Nice one. Have left a couple things up to you. Oo also the title needs updating now!

2024-08-26 07:05 UTC, kongzii requested changes

2024-08-26 07:05 UTC, kongzii commented on prediction_market_agent_tooling/deploy/agent.py
> +    def calculate_bet_amount(
Is this older version still used? I can't find usage of it anywhere

2024-08-26 23:32 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/agent.py
> +    def calculate_bet_amount(
thanks, removed

2024-08-26 23:34 UTC, gabrielfior commented on prediction_market_agent_tooling/tools/betting_strategies/kelly_criterion.py
> +        bet_direction = True
This was discussed in another thread (can't remember which one from the 80 comments) - if you have specific concerns, happy to open a new PR to discuss having "YES" or True.

2024-08-26 23:35 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +        # We add a new default here because it represents an upper bound.
Implemented, removed

2024-08-26 23:36 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +    def __init__(self, bet_amount: float | None = None):
done

2024-08-26 23:36 UTC, gabrielfior commented on pyproject.toml
> +ape-foundry = "^0.8.4"
reverted upgrade

2024-08-26 23:36 UTC, gabrielfior commented on prediction_market_agent_tooling/deploy/betting_strategy.py
> +    def get_max_bet_amount_for_market() -> float:
implemented

2024-08-27 07:22 UTC, kongzii approved these changes

2024-08-27 12:17 UTC, merged